// <auto-generated />
using System;
using System.Collections.Generic;
using Charwiki.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Charwiki.WebApi.Migrations
{
    [DbContext(typeof(CharwikiDbContext))]
    [Migration("20240930211538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Charwiki.ClassLib.Models.Loomian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type1")
                        .HasColumnType("integer");

                    b.Property<int?>("Type2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Loomians");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoomianAbilities");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoomianItems");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LoomianMoves");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoomianId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Move1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Move2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Move3Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Move4Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OtherOptions")
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .HasColumnType("text");

                    b.Property<List<string>>("Strengths")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Weaknesses")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LoomianId");

                    b.HasIndex("Move1Id");

                    b.HasIndex("Move2Id");

                    b.HasIndex("Move3Id");

                    b.HasIndex("Move4Id");

                    b.ToTable("LoomianSets");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.ValueToStatAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoomianSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoomianSetId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoomianSetId2")
                        .HasColumnType("uuid");

                    b.Property<int>("Stat")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoomianSetId");

                    b.HasIndex("LoomianSetId1");

                    b.HasIndex("LoomianSetId2");

                    b.ToTable("ValueToStatAssignments");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianSet", b =>
                {
                    b.HasOne("Charwiki.ClassLib.Models.LoomianAbility", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Charwiki.ClassLib.Models.LoomianItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Charwiki.ClassLib.Models.Loomian", "Loomian")
                        .WithMany()
                        .HasForeignKey("LoomianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Charwiki.ClassLib.Models.LoomianMove", "Move1")
                        .WithMany()
                        .HasForeignKey("Move1Id");

                    b.HasOne("Charwiki.ClassLib.Models.LoomianMove", "Move2")
                        .WithMany()
                        .HasForeignKey("Move2Id");

                    b.HasOne("Charwiki.ClassLib.Models.LoomianMove", "Move3")
                        .WithMany()
                        .HasForeignKey("Move3Id");

                    b.HasOne("Charwiki.ClassLib.Models.LoomianMove", "Move4")
                        .WithMany()
                        .HasForeignKey("Move4Id");

                    b.Navigation("Ability");

                    b.Navigation("Item");

                    b.Navigation("Loomian");

                    b.Navigation("Move1");

                    b.Navigation("Move2");

                    b.Navigation("Move3");

                    b.Navigation("Move4");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.ValueToStatAssignment", b =>
                {
                    b.HasOne("Charwiki.ClassLib.Models.LoomianSet", null)
                        .WithMany("PersonalityModifiers")
                        .HasForeignKey("LoomianSetId");

                    b.HasOne("Charwiki.ClassLib.Models.LoomianSet", null)
                        .WithMany("TrainingPoints")
                        .HasForeignKey("LoomianSetId1");

                    b.HasOne("Charwiki.ClassLib.Models.LoomianSet", null)
                        .WithMany("UniquePoints")
                        .HasForeignKey("LoomianSetId2");
                });

            modelBuilder.Entity("Charwiki.ClassLib.Models.LoomianSet", b =>
                {
                    b.Navigation("PersonalityModifiers");

                    b.Navigation("TrainingPoints");

                    b.Navigation("UniquePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
