// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VewTech.Charwiki.API;

#nullable disable

namespace VewTech.Charwiki.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231017070555_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.HeldItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeldItems");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Loomian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("ImageUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoomipediaNumber")
                        .HasColumnType("int");

                    b.Property<int>("MeeleeAttack")
                        .HasColumnType("int");

                    b.Property<int>("MeeleeDefense")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RangedAttack")
                        .HasColumnType("int");

                    b.Property<int>("RangedDefense")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Type1")
                        .HasColumnType("int");

                    b.Property<int>("Type2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Loomians");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.LoomianAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoomianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoomianId");

                    b.ToTable("LoomianAbilities");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AbilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnergyTP")
                        .HasColumnType("int");

                    b.Property<int>("EnergyUP")
                        .HasColumnType("int");

                    b.Property<int>("GameVersion")
                        .HasColumnType("int");

                    b.Property<int>("HealthTP")
                        .HasColumnType("int");

                    b.Property<int>("HealthUP")
                        .HasColumnType("int");

                    b.Property<Guid?>("LoomianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MeeleeAttackTP")
                        .HasColumnType("int");

                    b.Property<int>("MeeleeAttackUP")
                        .HasColumnType("int");

                    b.Property<int>("MeeleeDefenseTP")
                        .HasColumnType("int");

                    b.Property<int>("MeeleeDefenseUP")
                        .HasColumnType("int");

                    b.Property<int>("Personality1")
                        .HasColumnType("int");

                    b.Property<int>("Personality2")
                        .HasColumnType("int");

                    b.Property<int>("Personality3")
                        .HasColumnType("int");

                    b.Property<int>("RangedAttackTP")
                        .HasColumnType("int");

                    b.Property<int>("RangedAttackUP")
                        .HasColumnType("int");

                    b.Property<int>("RangedDefenseTP")
                        .HasColumnType("int");

                    b.Property<int>("RangedDefenseUP")
                        .HasColumnType("int");

                    b.Property<int>("SpeedTP")
                        .HasColumnType("int");

                    b.Property<int>("SpeedUP")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("LoomianId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.LoomianAbility", b =>
                {
                    b.HasOne("VewTech.Charwiki.Library.Models.Loomian", null)
                        .WithMany("Abilities")
                        .HasForeignKey("LoomianId");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Move", b =>
                {
                    b.HasOne("VewTech.Charwiki.Library.Models.Set", null)
                        .WithMany("Moveset")
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Set", b =>
                {
                    b.HasOne("VewTech.Charwiki.Library.Models.LoomianAbility", "Ability")
                        .WithMany()
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VewTech.Charwiki.Library.Models.Loomian", null)
                        .WithMany("Sets")
                        .HasForeignKey("LoomianId");

                    b.Navigation("Ability");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Loomian", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("VewTech.Charwiki.Library.Models.Set", b =>
                {
                    b.Navigation("Moveset");
                });
#pragma warning restore 612, 618
        }
    }
}
